import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { SyncPill, commonStyles } from "@/components/health/ui";
import { useHealth } from "@/lib/health/store";
import type { Medicine } from "@/lib/health/types";

export default function MedicinesScreen() {
  const { state, t, recordInventoryTransaction } = useHealth();
  const [selected, setSelected] = useState<Medicine | undefined>();
  const medicines = [...state.medicines].sort((a, b) => (a.stock <= a.minimumStock ? -1 : 1) - (b.stock <= b.minimumStock ? -1 : 1));
  const adjust = (medicine: Medicine, type: "receipt" | "dispense") => { recordInventoryTransaction(medicine.id, type, type === "receipt" ? 10 : 1); Alert.alert(type === "receipt" ? "Receipt recorded locally" : "Dispense recorded locally", `${medicine.name} is marked pending sync.`); };
  return <View style={commonStyles.screen}><FlatList data={medicines} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><Text style={commonStyles.eyebrow}>Pharmacy workflow</Text><Text style={commonStyles.title}>{t("medicines")}</Text><Text style={[commonStyles.body, { marginTop: 5, marginBottom: 15 }]}>Transaction-based availability. Do not treat last-synchronised stock as a guaranteed supply.</Text><View style={styles.alert}><MaterialIcons name="inventory-2" size={19} color="#9A5B00"/><Text style={styles.alertText}>{medicines.filter((item) => item.stock <= item.minimumStock).length} medicines need stock attention</Text></View></>} renderItem={({ item }) => <Pressable onPress={() => setSelected(selected?.id === item.id ? undefined : item)} style={({ pressed }) => [commonStyles.card, styles.card, { opacity: pressed ? 0.72 : 1 }]}><View style={styles.top}><View style={styles.flex}><Text style={styles.name}>{item.name}</Text><Text style={commonStyles.tiny}>{item.localName} · {item.unit}</Text></View><StockBadge medicine={item}/></View><View style={styles.stockRow}><Text style={styles.stockNumber}>{item.stock}</Text><Text style={styles.stockUnit}>{item.unit}</Text><View style={styles.flex}/><Text style={styles.expiry}>{item.expiryDays < 30 ? `Expires in ${item.expiryDays} days` : `Min. ${item.minimumStock}`}</Text></View><View style={styles.bottom}><SyncPill state={item.syncState}/><Text style={styles.stale}>{item.syncState === "synced" ? t("stockAvailable") : t("staleStock")}</Text></View>{selected?.id === item.id && <View style={styles.actions}><Pressable onPress={() => adjust(item, "receipt")} style={({ pressed }) => [styles.stockAction, { opacity: pressed ? 0.65 : 1 }]}><MaterialIcons name="add-circle-outline" size={17} color="#087E7B"/><Text style={styles.stockActionText}>{t("received")} +10</Text></Pressable><Pressable onPress={() => adjust(item, "dispense")} disabled={item.stock === 0} style={({ pressed }) => [styles.stockAction, { opacity: item.stock === 0 ? 0.35 : pressed ? 0.65 : 1 }]}><MaterialIcons name="remove-circle-outline" size={17} color="#087E7B"/><Text style={styles.stockActionText}>{t("dispensed")} −1</Text></Pressable></View>}</Pressable>} /></View>;
}
function StockBadge({ medicine }: { medicine: Medicine }) { const isOut = medicine.stock === 0; const isLow = medicine.stock > 0 && medicine.stock <= medicine.minimumStock; const label = isOut ? "Out of stock" : isLow ? "Low stock" : "Available"; const tone = isOut ? { background: "#FDECEC", text: "#B42318", icon: "error-outline" as const } : isLow ? { background: "#FFF4E5", text: "#9A5B00", icon: "warning-amber" as const } : { background: "#EEF6F0", text: "#198754", icon: "check-circle" as const }; return <View style={[styles.badge, { backgroundColor: tone.background }]}><MaterialIcons name={tone.icon} size={14} color={tone.text}/><Text style={[styles.badgeText, { color: tone.text }]}>{label}</Text></View>; }
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 36, gap: 10 }, alert: { alignItems: "center", backgroundColor: "#FFF4E5", borderRadius: 13, flexDirection: "row", gap: 8, marginBottom: 7, padding: 12 }, alertText: { color: "#9A5B00", fontSize: 13, fontWeight: "900" }, card: { marginTop: 3 }, top: { alignItems: "center", flexDirection: "row", gap: 8, justifyContent: "space-between" }, flex: { flex: 1 }, name: { color: "#18332F", fontSize: 16, fontWeight: "900" }, badge: { alignItems: "center", borderRadius: 999, flexDirection: "row", gap: 4, paddingHorizontal: 8, paddingVertical: 5 }, badgeText: { fontSize: 11, fontWeight: "900" }, stockRow: { alignItems: "flex-end", flexDirection: "row", marginTop: 13 }, stockNumber: { color: "#18332F", fontSize: 28, fontWeight: "900" }, stockUnit: { color: "#6C817C", fontSize: 12, fontWeight: "800", marginBottom: 5, marginLeft: 5 }, expiry: { color: "#B66A00", fontSize: 11, fontWeight: "800", marginBottom: 6 }, bottom: { alignItems: "center", borderTopColor: "#E7EEEB", borderTopWidth: 1, flexDirection: "row", gap: 8, marginTop: 10, paddingTop: 10 }, stale: { color: "#6C817C", fontSize: 11, fontWeight: "700" }, actions: { borderTopColor: "#E7EEEB", borderTopWidth: 1, flexDirection: "row", gap: 10, marginTop: 12, paddingTop: 11 }, stockAction: { alignItems: "center", backgroundColor: "#E6F5F3", borderRadius: 10, flex: 1, flexDirection: "row", gap: 5, justifyContent: "center", minHeight: 38 }, stockActionText: { color: "#087E7B", fontSize: 12, fontWeight: "900" } });
