import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { SyncPill, commonStyles } from "@/components/health/ui";
import { useHealth } from "@/lib/health/store";

export default function PatientsScreen() {
  const { state, t } = useHealth();
  const [query, setQuery] = useState("");
  const results = useMemo(() => state.patients.filter((patient) => `${patient.name} ${patient.localId}`.toLowerCase().includes(query.toLowerCase())), [query, state.patients]);
  return <View style={commonStyles.screen}><FlatList data={results} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><Text style={commonStyles.eyebrow}>Longitudinal records</Text><Text style={commonStyles.title}>{t("patients")}</Text><View style={styles.search}><MaterialIcons name="search" size={20} color="#54716B"/><TextInput value={query} onChangeText={setQuery} style={styles.searchInput} placeholder={t("searchPatients")} placeholderTextColor="#8CA19B" /></View></>} renderItem={({ item }) => <Pressable onPress={() => router.push(`/patient/${item.id}` as never)} style={({ pressed }) => [commonStyles.card, styles.card, { opacity: pressed ? 0.7 : 1 }]}><View style={styles.avatar}><Text style={styles.avatarText}>{item.name.split(" ").map((part) => part[0]).slice(0, 2).join("")}</Text></View><View style={styles.flex}><Text style={styles.name}>{item.name}</Text><Text style={commonStyles.tiny}>{item.localId} · {item.age} years</Text><View style={styles.tags}>{item.careTags.map((tag) => <Text key={tag} style={styles.tag}>{t(tag)}</Text>)}</View></View><View style={styles.end}><SyncPill state={item.syncState}/><MaterialIcons name="chevron-right" size={23} color="#6C817C"/></View></Pressable>} ListEmptyComponent={<View style={[commonStyles.card, styles.empty]}><Text style={commonStyles.body}>No local record matches that search.</Text></View>}/><Pressable accessibilityRole="button" accessibilityLabel={t("registerPatient")} onPress={() => router.push("/register" as never)} style={({ pressed }) => [styles.fab, { opacity: pressed ? 0.75 : 1, transform: [{ scale: pressed ? 0.98 : 1 }] }]}><MaterialIcons name="person-add" size={21} color="#FFFFFF"/><Text style={styles.fabText}>{t("registerPatient")}</Text></Pressable></View>;
}
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 104, gap: 9 }, search: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#D5E1DD", borderRadius: 13, borderWidth: 1, flexDirection: "row", gap: 8, marginVertical: 17, minHeight: 50, paddingHorizontal: 13 }, searchInput: { color: "#18332F", flex: 1, fontSize: 15 }, card: { alignItems: "center", flexDirection: "row", gap: 10 }, avatar: { alignItems: "center", backgroundColor: "#E6F5F3", borderRadius: 15, height: 45, justifyContent: "center", width: 45 }, avatarText: { color: "#087E7B", fontSize: 14, fontWeight: "900" }, flex: { flex: 1 }, name: { color: "#18332F", fontSize: 15, fontWeight: "900" }, tags: { flexDirection: "row", flexWrap: "wrap", gap: 5, marginTop: 5 }, tag: { color: "#087E7B", fontSize: 10, fontWeight: "800" }, end: { alignItems: "flex-end", gap: 5 }, fab: { alignItems: "center", backgroundColor: "#087E7B", borderRadius: 999, bottom: 18, flexDirection: "row", gap: 7, paddingHorizontal: 18, minHeight: 50, position: "absolute", right: 16, shadowColor: "#18332F", shadowOpacity: 0.18, shadowRadius: 10, shadowOffset: { width: 0, height: 5 }, elevation: 5 }, fabText: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" }, empty: { alignItems: "center", padding: 22 } });
