import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { PrimaryButton, PriorityBadge, SyncPill, LiveQueueBanner, commonStyles } from "@/components/health/ui";
import { useHealth } from "@/lib/health/store";
import { sortQueue } from "@/lib/health/workflows";

const facilityId = Number(process.env.EXPO_PUBLIC_FACILITY_ID ?? 0);

export default function QueueScreen() {
  const { state, t, updateQueueStatus, priorityReasonLabel } = useHealth();
  const entries = sortQueue(state.queue.filter((item) => item.status !== "completed"));
  const callNext = () => { const next = entries.find((entry) => entry.status === "waiting"); if (next) updateQueueStatus(next.id, "called"); };
  return <View style={commonStyles.screen}><FlatList data={entries} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<>{facilityId > 0 && <LiveQueueBanner facilityId={facilityId}/>}<Text style={commonStyles.eyebrow}>Live service board</Text><Text style={commonStyles.title}>{t("queue")}</Text><Text style={[commonStyles.body, { marginTop: 5, marginBottom: 15 }]}>Priority first, then first-in-first-out within each category.</Text><PrimaryButton label={t("callNext")} icon="campaign" onPress={callNext} disabled={!entries.some((entry) => entry.status === "waiting")}/><View style={styles.summary}><MaterialIcons name="groups" size={19} color="#087E7B"/><Text style={styles.summaryText}>{entries.length} patients active · {entries.filter((entry) => entry.priority === "emergency" || entry.priority === "urgent").length} high-risk</Text></View></>} renderItem={({ item, index }) => { const patient = state.patients.find((record) => record.id === item.patientId); if (!patient) return null; const minutes = Math.max(1, Math.round((Date.now() - item.arrivedAt) / 60000)); return <Pressable onPress={() => router.push(`/patient/${patient.id}` as never)} style={({ pressed }) => [commonStyles.card, styles.card, { opacity: pressed ? 0.72 : 1 }]}><View style={styles.topRow}><Text style={styles.token}>#{String(index + 1).padStart(2, "0")}</Text><PriorityBadge priority={item.priority} compact /></View><Text style={styles.name}>{patient.name}</Text><Text style={commonStyles.body}>{patient.localId} · {item.service}</Text><Text style={styles.reason}>{priorityReasonLabel(item.priorityReason)}</Text><View style={styles.footer}><View><Text style={commonStyles.tiny}>{minutes} min waiting · {t(item.status)}</Text><View style={{ marginTop: 7 }}><SyncPill state={item.syncState}/></View></View><Pressable onPress={() => updateQueueStatus(item.id, item.status === "waiting" ? "called" : "completed")} style={({ pressed }) => [styles.action, { opacity: pressed ? 0.65 : 1 }]}><Text style={styles.actionText}>{item.status === "waiting" ? t("callNext") : "Complete"}</Text><MaterialIcons name={item.status === "waiting" ? "campaign" : "check-circle"} size={17} color="#087E7B"/></Pressable></View></Pressable>; }} ListEmptyComponent={<View style={[commonStyles.card, styles.empty]}><Text style={commonStyles.body}>{t("noQueue")}</Text></View>}/></View>;
}
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 36, gap: 10 }, summary: { alignItems: "center", backgroundColor: "#E6F5F3", borderRadius: 13, flexDirection: "row", gap: 8, marginVertical: 14, padding: 12 }, summaryText: { color: "#087E7B", fontSize: 13, fontWeight: "800" }, card: { marginBottom: 2 }, topRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, token: { color: "#6C817C", fontSize: 12, fontWeight: "900" }, name: { color: "#18332F", fontSize: 18, fontWeight: "900", marginTop: 10 }, reason: { color: "#B66A00", fontSize: 12, fontWeight: "800", marginTop: 6 }, footer: { alignItems: "flex-end", borderTopColor: "#E7EEEB", borderTopWidth: 1, flexDirection: "row", justifyContent: "space-between", marginTop: 12, paddingTop: 10 }, action: { alignItems: "center", flexDirection: "row", gap: 5, minHeight: 32 }, actionText: { color: "#087E7B", fontSize: 12, fontWeight: "900" }, empty: { alignItems: "center", marginTop: 18, padding: 22 } });
