import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { PrimaryButton, PriorityBadge, SyncPill, commonStyles } from "@/components/health/ui";
import { useHealth } from "@/lib/health/store";
import { canTransitionReferral, nextReferralStatuses } from "@/lib/health/workflows";
import type { ReferralStatus } from "@/lib/health/types";

export default function ReferralsScreen() {
  const { state, t, referralLabel, updateReferralStatus } = useHealth() as ReturnType<typeof useHealth> & { referralLabel?: (status: ReferralStatus) => string };
  const label = referralLabel ?? ((status: ReferralStatus) => status.replace(/([A-Z])/g, " $1"));
  const referrals = [...state.referrals].sort((a, b) => b.updatedAt - a.updatedAt);
  return <View style={commonStyles.screen}><FlatList data={referrals} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><Text style={commonStyles.eyebrow}>Care coordination</Text><Text style={commonStyles.title}>{t("referrals")}</Text><Text style={[commonStyles.body, { marginTop: 5, marginBottom: 16 }]}>Track destination, handoff, and follow-up without losing locally captured updates.</Text><PrimaryButton label={t("createReferral")} icon="send" onPress={() => router.push("/referral/new" as never)} /></>} renderItem={({ item }) => { const patient = state.patients.find((record) => record.id === item.patientId); const next = nextReferralStatuses(item.status)[0]; return <View style={[commonStyles.card, styles.card]}><View style={styles.top}><View style={styles.flex}><Text style={styles.destination}>{item.destination}</Text><Text style={commonStyles.tiny}>{patient?.name ?? "Unknown patient"} · {patient?.localId ?? ""}</Text></View><PriorityBadge priority={item.urgency} compact /></View><View style={styles.route}><View style={styles.routeDot}/><View style={styles.routeLine}/><MaterialIcons name="local-hospital" size={19} color="#2369A5"/></View><Text style={styles.reason}>{item.reason}</Text><View style={styles.footer}><View><Text style={styles.status}>{label(item.status)}</Text><View style={{ marginTop: 6 }}><SyncPill state={item.syncState}/></View></View>{next && canTransitionReferral(item.status, next) && <Pressable onPress={() => updateReferralStatus(item.id, next)} style={({ pressed }) => [styles.advance, { opacity: pressed ? 0.65 : 1 }]}><Text style={styles.advanceText}>{t("update")}</Text><MaterialIcons name="arrow-forward" size={16} color="#087E7B"/></Pressable>}</View></View>; }} ListEmptyComponent={<View style={[commonStyles.card, styles.empty]}><Text style={commonStyles.body}>No referrals are recorded locally.</Text></View>}/></View>;
}
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 36, gap: 10 }, card: { marginTop: 9 }, flex: { flex: 1 }, top: { flexDirection: "row", gap: 8, justifyContent: "space-between" }, destination: { color: "#18332F", fontSize: 16, fontWeight: "900" }, route: { alignItems: "center", flexDirection: "row", height: 31, marginTop: 9, width: 116 }, routeDot: { backgroundColor: "#087E7B", borderRadius: 5, height: 10, width: 10 }, routeLine: { backgroundColor: "#B9D6D1", height: 2, width: 65 }, reason: { color: "#54716B", fontSize: 13, lineHeight: 18 }, footer: { alignItems: "flex-end", borderTopColor: "#E7EEEB", borderTopWidth: 1, flexDirection: "row", justifyContent: "space-between", marginTop: 12, paddingTop: 10 }, status: { color: "#2369A5", fontSize: 13, fontWeight: "900", textTransform: "capitalize" }, advance: { alignItems: "center", flexDirection: "row", gap: 4, minHeight: 32 }, advanceText: { color: "#087E7B", fontSize: 12, fontWeight: "900" }, empty: { alignItems: "center", marginTop: 18, padding: 22 } });
